using FundAppDomain.ApplicationServices;
using FundAppDomain.Model.AbstractStocks;
using FundAppDomain.Repositories;
using FundAppDomainTests.Tools;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using Moq;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Linq.Expressions;
using System.Text;
using System.Threading.Tasks;

namespace FundAppDomainTests.Tests
{
    [TestClass]
    public class StockNamingTests
    {

        #region Test methods

        [TestMethod]
        [TestCategory("domainTest")]
        public void StockNamesAreAutogeneratedInSequence()
        {
            InMemoryDomain.DoTest(rootDomainService =>
            {
                rootDomainService.StockEntitiesService.AddEquity(1, 3);
                rootDomainService.StockEntitiesService.AddEquity(1, 3);

                rootDomainService.StockEntitiesService.AddBond(1, 3);
                var stocks = rootDomainService.StockEntitiesService.ListStocks().ToList();


                Assert.AreEqual("Equity1", stocks[0].Name);
                Assert.AreEqual("Equity2", stocks[1].Name);
                Assert.AreEqual("Bond1", stocks[2].Name);
            });

        }

        #endregion
    }
}
